### ISSUE TITLE
When cancel order there is no void transaction in magento and payment status not updated

### ISSUE THREAD

**Issue by likemusic** [checkout/checkout-magento2-plugin#92] opened 2019-03-24 02:38 UTC
When close order there is no void transaction in magento and payment status not updated.
![image](https://user-images.githubusercontent.com/603401/54874153-a2cabd00-4df6-11e9-9c0a-e0758ee725a9.png)

I'm not sure, but seems that voided authorized payment should exists in "Transactions" table for order (in magento admin).
![image](https://user-images.githubusercontent.com/603401/54874161-c55cd600-4df6-11e9-9e34-f22da1752922.png)

Also in "Payment Information" table status is "Authorized", but seems that it shoud be "Voided" for canceled orders.
![image](https://user-images.githubusercontent.com/603401/54874168-de658700-4df6-11e9-9935-abf60a664534.png)

**Comment by likemusic** [comment] 2019-03-24 02:48
Its happens because for action on "Void" order payment button used \CheckoutCom\Magento2\Gateway\Http\Client\VoidTransaction, but for void on "Cancel" button used \CheckoutCom\Magento2\Model\Service\OrderService::cancelTransactionToRemote().

Seems that we have 2 points in code to call the same API methods on checkout.com. It's bad practice. Call to the same Api shoud be incapsulated in one method/class that should be injected and called from different ponts in code.

**Comment by david-fiaty-cko** [comment] 2019-03-25 10:55
@likemusic, answers point by point below:

1- When close order there is no void transaction in magento and payment status not updated
Closing an order is not supposed to void a transaction. In order to void a transaction, you have to use the credit memo system

2- I'm not sure, but seems that voided authorized payment should exists in "Transactions" table for order (in magento admin).
There is no "Void" or "Refund" transaction type in Magento2. Only "authorized" and "captured"

3- Also in "Payment Information" table status is "Authorized", but seems that it shoud be "Voided" for canceled orders.
This section is showing the information about the first transaction that was processed with he order. Other transactions that happen after are not supposed to be displayed there.

4- \CheckoutCom\Magento2\Gateway\Http\Client\VoidTransaction is deprecated code meant to disappear in an upcoming release.

Closing this as there are no issues to fix.

**Comment by likemusic** [comment] 2019-03-25 11:54
@david-fiaty-cko 

> >1- When close order there is no void transaction in magento and payment status not updated

> Closing an order is not supposed to void a transaction. In order to void a transaction, you have to use the credit memo system

I'm sorry, I told about "Close" order operation. In this case authorized payment voided by [\CheckoutCom\Magento2\Observer\OrderCancelObserver](https://github.com/checkout/checkout-magento2-plugin/blob/master/Observer/OrderCancelObserver.php). I renamed "close" to "cancel" in issue title right now.

**Comment by likemusic** [comment] 2019-03-25 11:54
>>2- I'm not sure, but seems that voided authorized payment should exists in "Transactions" table for order (in magento admin).

> There is no "Void" or "Refund" transaction type in Magento2. Only "authorized" and "captured"

Seem't that you're wrong. Please look at [\Magento\Sales\Api\Data\TransactionInterface](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Api/Data/TransactionInterface.php):

```
...
interface TransactionInterface extends \Magento\Framework\Api\ExtensibleDataInterface
{
    /**#@+
     * Supported transaction types
     * @var string
     */
    const TYPE_PAYMENT = 'payment';

    const TYPE_ORDER = 'order';

    const TYPE_AUTH = 'authorization';

    const TYPE_CAPTURE = 'capture';

    const TYPE_VOID = 'void';

    const TYPE_REFUND = 'refund';
...
```

**Comment by likemusic** [comment] 2019-03-25 11:55
> 3- Also in "Payment Information" table status is "Authorized", but seems that it shoud be "Voided" for canceled orders.

>> This section is showing the information about the first transaction that was processed with he order. Other transactions that happen after are not supposed to be displayed there.

But why? It is not obvious. It's seems like anothe bug in this module implementation. What sense to show for admin status payment "authorized", when it was already captured, or voided or refunded?
Why it's not show real current state of payment?

**Comment by david-fiaty-cko** [comment] 2019-03-26 10:16
@likemusic yes indeed there are void and refund transaction types.
For the order status, this is the way Magento 2 works as far as I know. You can try updating an order status. It will be updated everywhere but not there.

**Comment by david-fiaty-cko** [comment] 2019-03-26 14:06
@likemusic it seems that the payment information is stored in the order details (payment information) by providing an array at the order creation. 

This is the reason why the initial status assigned to the order is not updated in the payment information section, as the module doesn't directly edit the array in case of order status update.

The issue is reopened to see if it's a good approach to edit the initial payment information, as each transaction information is available in the transaction details.

I will keep you updated on this one. Thank you for the suggestion.

**Comment by david-fiaty-cko** [comment] 2019-04-04 10:22
@likemusic, for clarification:
Cancelling an order doesn't mean that the associated transactions should be voided (authorisation) or refunded (capture). Voiding or refunding a transaction should be explicit.

Magento 2 offers the possibility to void a transaction or to refund a transaction. Cancelling an order shouldn't trigger implicitly a void or refund.

Please follow the link below to see how the void feature is implemented in Magento 2.
https://mage2.pro/t/topic/938

I am closing this for now. Please comment further if this is not clear. Thank you.

**Closed as completed by david-fiaty-cko** 2019-04-04 10:22 UTC
