### ISSUE TITLE
Info about webhook and their configuration in readme required for plugin well work

### ISSUE THREAD

**Issue by likemusic** [checkout/checkout-magento2-plugin#94] opened 2019-03-24 03:08 UTC
Endpoint should have webhook to change order status automaticaly according to plugin config . At the moment there is no info about it in readme.

Also a found that webhook controller acceps only limited types of events: 
 - refund
 - void
 - authorize
- capture

All other event types could/should be disabled for webhook.

Imho, this info should be added to the readme, to prevent trubles with this plugin for users.

**Comment by david-fiaty-cko** [comment] 2019-03-24 12:16
@likemusic, the webhooks are a more a Checkout.com Gateway feature than a Magento 2 module feature. Comprehensive information on how the web hooks work is available in the official Checkout.com documentation: https://docs.checkout.com/docs/webhook-management

In this documentation, you will find the following list of supported gateway events:
"payment_approved"
"payment_flagged"
"payment_pending"
"payment_declined"
"payment_expired"
"payment_cancelled"
"payment_voided"
"payment_void_declined"
"payment_captured"
"payment_capture_declined"
"payment_capture_pending"
"payment_refunded"
"payment_refund_declined"
"payment_refund_pending"
"payment_chargeback"
"payment_retrieval"

All these event types are normally handled in the Magento 2 module.
Could you please specify which event is causing an issue?

**Comment by likemusic** [comment] 2019-03-25 09:58
@david-fiaty-cko listed abobe events - are events from newest api, that not supported by this magento module at all, as I can see by source code.

Event types that should be supported by this plugin listed in docs for classic Api here: https://archive.docs.checkout.com/docs/broadcast-webhooks

Event Types
- charge.succeeded
- charge.failed
- charge.captured
- charge.captured.failed
- charge.refunded
- charge.refunded.failed
- charge.voided
- charge.voided.failed
- charge.retrieval
- charge.chargeback
- charge.captured.deferred
- charge.pending
- invoice.cancelled

From list above really suppoted events is (see [Model/Adapter/CallbackEventAdapter.php](https://github.com/checkout/checkout-magento2-plugin/blob/master/Model/Adapter/CallbackEventAdapter.php)):
 - charge.succeeded > authorize
 - charge.captured > capture
 - charge.refunded > refund
 - charge.voided > void


They are required to be enabled in webhook config in hub or sandbox.

All other events just skipped in webhook controller, they are not necessary to be enabled in webhook config (see [Model/Service/CallbackService.php](https://github.com/checkout/checkout-magento2-plugin/blob/master/Model/Service/CallbackService.php)).

**Comment by david-fiaty-cko** [comment] 2019-03-25 10:47
@likemusic , yes indeed there is an error in the link I sent to you and I'm glad you found the right page int the archives. 

The module does update the order status according to the config. The explanations about the feature is in the "Order settings section".

The events processed in the callback service are indeed charge.succeeded, charge.captured, charge.refunded, charge.voided, which are the ones who need one of these operations:
- Send an email
- Create transactions
- Update an order status
- Create an invoice

The other events you mention are not missing. They just don't require a specific operation on the order. However the response from the gateway is logged and the admin has information about the event.

For example, a charge.voided.failed event doesn't need an action on the order because the transaction of the order was authorised. If the void fails, we just add the info that the void failed, but there is no action to perform on the order.

Same with a charge.refunded.failed, there is no action to perform as the status was the one of a captured order transaction.

No event is or should be skipped, some of them just don't need any actions on orders, just logging.
I am closing this as there seems to be no issue to fix here.

**Comment by likemusic** [comment] 2019-03-25 12:50
@david-fiaty-cko , info that you provide above very helpfull, and I this that it should be added to the readme file. Something like this:

```
Webhook should be created in hub or sendbox with url shown in module config in `Callbacks URLs` section in "Webhook Url" read-only text field.
For this webhook events listed below should be enabled to keep order status related to module configs in "Order Settings" section:
- Successful authorizations
- Successful captures
- Successful refunds
- Successful voids


All other events could be enabled just for logging purpose on Magento side.
```

What do you think about it?


> However the response from the gateway is logged and the admin has information about the event.

Seems that logging not used in webhook controller at all. I couldn't find it both in `\CheckoutCom\Magento2\Controller\Webhook\Callback` and `\CheckoutCom\Magento2\Model\Service\CallbackService`.

Also I set breakpoints for all logger using in this module and not catch anyone in webook processing.

I think new issue should be created for this.

**Comment by david-fiaty-cko** [comment] 2019-03-26 13:57
@likemusic, this issue is reopened until the readme file has the additions suggested.
About the logging, the transaction information is currently stored in the order details at a transaction level. This could be indeed be improved with logging in var/log, which will be added in an upcoming release.

**Comment by likemusic** [comment] 2019-03-26 14:13
> the transaction information is currently stored in the order details at a transaction level

@david-fiaty-cko Transation information created in placeOrder-controller. No transactions created upon any webhook calls.

**Comment by david-fiaty-cko** [comment] 2019-04-04 11:41
@likemusic, it's confirmed that the only web hooks that require specific business logic on the orders are the following:
- charge.succeeded > authorize
- charge.captured > capture
- charge.refunded > refund
- charge.voided > void

The other webhooks you have listed are simply informative on the Magento 2 level and there is no specific action to take on orders or transactions.

For example, if a void fails, there is no modification on the previously created auth transaction.
The best we can do is add a comment to the order to show that the void has failed.

As a consequence, complementary information has been added to the CallbackService class for each webhook, as seen below. This code snipped will tell you precisely what happens for each one of these informative webhooks.

This update is available on the dev branch and will be released on master next week. I am closing this issue now, please comment further if needed.

```$msg = '';
switch ($commandName) {
    case 'charge.failed':
    $msg = 'The transaction authorisation could not be completed.';
    break;

    case 'charge.captured.failed':
    $msg = 'The transaction capture could not be completed.';
    break;

    case 'charge.refunded.failed':
    $msg = 'The captured transaction could not be refunded.';
    break;

    case 'charge.voided.failed':
    $msg = 'The authorised transaction could not be voided.';
    break;

    case 'charge.retrieval':
    $msg = 'The charge retrieval has been completed.';
    break;

    case 'charge.chargeback':
    $msg = 'The chargeback has been completed.';
    break;

    case 'charge.captured.deferred':
    $msg = 'The capture has been deferred.';
    break;

    case 'charge.pending':
    $msg = 'The charge is pending.';
    break;

    case 'invoice.cancelled':
    $msg = 'The Alternative Payment Method transaction has expired.';
    break;
}

// Add a comment to history
if (!empty($msg)) {
    $order->addStatusToHistory($order->getStatus(), __($msg), $notify = true);
    $order->save();
}`

**Closed as completed by david-fiaty-cko** 2019-04-04 11:41 UTC
