### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in /chroot/home/ininefiv/ecommerce-for-erp.com/html/vendor/checkoutcom/magento2/Model/Service/VersionHandlerService.php on line 143

### ISSUE THREAD

**Issue by vikasi95dev** [checkout/checkout-magento2-plugin#248] opened 2020-03-31 09:13 UTC
Hello Team,

I have noticed below error after installing the extension on Magento 2.3.4 Open Source. Can you please look into this.

Warning: count(): Parameter must be an array or an object that implements Countable in /chroot/home/ininefiv/ecommerce-for-erp.com/html/vendor/checkoutcom/magento2/Model/Service/VersionHandlerService.php on line 143

**Comment by david-fiaty-cko** [comment] 2020-04-01 05:59
@vikasi95dev, this issue seems to be a duplicate of https://github.com/checkout/checkout-magento2-plugin/issues/237. 

I'm closing this one but please feel free to post your questions there if needed. Thank you.

**Closed as completed by david-fiaty-cko** 2020-04-01 05:59 UTC
